## Level 1: Data Inspection

In [3]:
import numpy as np
import pandas as pd

# Make output reproducible
np.random.seed(42)

# Number of records
n = 100

# Generate random data
df = pd.DataFrame({
    "Order_ID": np.arange(1001, 1001+n),
    "Customer": np.random.choice(
        ["Amit", "Priya", "Rahul", "Neha", "Rohan", "Anjali", "Vikram", "Sneha", "Karan", "Meera"],
        n
    ),
    "City": np.random.choice(
        ["Delhi", "Mumbai", "Bangalore", "Hyderabad", "Pune", "Chennai"],
        n
    ),
    "Category": np.random.choice(
        ["Electronics", "Furniture", "Clothing"],
        n
    ),
    "Product": np.random.choice(
        ["Laptop", "Chair", "Mouse", "Table", "Keyboard", "Monitor",
         "Shoes", "Jacket", "Mobile", "Desk"],
        n
    ),
    "Quantity": np.random.randint(1, 6, n),
    "Price": np.random.randint(500, 50001, n),
    "Payment_Mode": np.random.choice(
        ["UPI", "Card", "COD", "EMI"],
        n
    ),
    "Status": np.random.choice(
        ["Delivered", "Pending", "Cancelled"],
        n,
        p=[0.7, 0.2, 0.1]
    ),
    "Discount": np.random.randint(0, 3001, n)
})

# Create Sales column
df["Sales"] = df["Quantity"] * df["Price"] - df["Discount"]

# Add some missing values
df.loc[np.random.choice(df.index, 5, replace=False), "Discount"] = np.nan
df.loc[np.random.choice(df.index, 3, replace=False), "City"] = np.nan

# Rearrange columns
df = df[
    [
        "Order_ID", "Customer", "City", "Category", "Product",
        "Quantity", "Price", "Discount", "Sales",
        "Payment_Mode", "Status"
    ]
]

# Save as CSV
df.to_csv("sales_data.csv", index=False)

### Load the dataset into a DataFrame ###

In [4]:
df

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered
1,1002,Neha,Mumbai,Clothing,Monitor,4,8043,671.0,31501,UPI,Delivered
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...
95,1096,Meera,Delhi,Clothing,Table,2,26932,2472.0,51392,EMI,Delivered
96,1097,Karan,Bangalore,Clothing,Chair,5,18249,2660.0,88585,Card,Delivered
97,1098,Vikram,Delhi,Furniture,Desk,2,41959,1541.0,82377,EMI,Delivered
98,1099,Karan,Mumbai,Clothing,Mouse,5,26756,2739.0,131041,Card,Pending
99,1100,Sneha,Mumbai,Furniture,Laptop,3,40762,1305.0,120981,EMI,Delivered

In [3]:
print(df.head())

   Order_ID Customer       City     Category  Product  Quantity  Price  \
0      1001   Vikram  Hyderabad    Furniture  Monitor         3    912
1      1002     Neha     Mumbai     Clothing  Monitor         4   8043
2      1003    Sneha      Delhi  Electronics    Mouse         2  40855
3      1004    Rohan    Chennai  Electronics  Monitor         2  33996
4      1005   Vikram       Pune  Electronics   Jacket         5  24048

   Discount   Sales Payment_Mode     Status
0      92.0    2644          UPI  Delivered
1     671.0   31501          UPI  Delivered
2    1969.0   79741          EMI  Cancelled
3      60.0   67932          EMI  Cancelled
4    2681.0  117559         Card  Delivered

### Display the first 10 rows. ###

In [6]:
df.head(10)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered
1,1002,Neha,Mumbai,Clothing,Monitor,4,8043,671.0,31501,UPI,Delivered
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered
5,1006,Meera,Bangalore,Clothing,Chair,2,27884,1028.0,54740,EMI,Delivered
6,1007,Rahul,Hyderabad,Furniture,Keyboard,5,44925,NaN,223136,COD,Delivered
7,1008,Vikram,Chennai,Furniture,Laptop,1,39256,603.0,38653,COD,Pending
8,1009,Sneha,Bangalore,Electronics,Laptop,4,19388,681.0,76871,UPI,Delivered
9,1010,Rohan,Bangalore,Furniture,Keyboard,5,36235,2581.0,178594,EMI,Delivered

## Display the last 7 rows.

In [7]:
df.tail(7)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
93,1094,Meera,Pune,Electronics,Shoes,1,14307,2795.0,11512,Card,Delivered
94,1095,Vikram,Delhi,Electronics,Jacket,4,42848,2642.0,168750,EMI,Delivered
95,1096,Meera,Delhi,Clothing,Table,2,26932,2472.0,51392,EMI,Delivered
96,1097,Karan,Bangalore,Clothing,Chair,5,18249,2660.0,88585,Card,Delivered
97,1098,Vikram,Delhi,Furniture,Desk,2,41959,1541.0,82377,EMI,Delivered
98,1099,Karan,Mumbai,Clothing,Mouse,5,26756,2739.0,131041,Card,Pending
99,1100,Sneha,Mumbai,Furniture,Laptop,3,40762,1305.0,120981,EMI,Delivered

## Find the total number of rows and columns.

In [13]:
df.shape

(100, 11)

In [21]:
Rows = df.shape[0]
Columns= df.shape[1]
print(Rows)
print(Columns)

100
11

## Display the names of all columns.

In [26]:
df.columns

Index(['Order_ID', 'Customer', 'City', 'Category', 'Product', 'Quantity',
       'Price', 'Discount', 'Sales', 'Payment_Mode', 'Status'],
      dtype='object')

## Check the datatype of each column.

In [28]:
df.dtypes

Order_ID          int64
Customer         object
City             object
Category         object
Product          object
Quantity          int32
Price             int32
Discount        float64
Sales             int32
Payment_Mode     object
Status           object
dtype: object

## Generate descriptive statistics for all numerical columns.

In [36]:
df.describe()

          Order_ID    Quantity         Price     Discount         Sales
count   100.000000  100.000000    100.000000    95.000000     100.00000
mean   1050.500000    3.090000  25577.690000  1533.105263   78863.70000
std      29.011492    1.450148  14125.367626   903.218577   63710.71279
min    1001.000000    1.000000    912.000000    27.000000     637.00000
25%    1025.750000    2.000000  14778.500000   676.000000   34187.75000
50%    1050.500000    3.000000  24100.500000  1603.000000   59634.50000
75%    1075.250000    4.250000  38026.250000  2277.500000  114852.00000
max    1100.000000    5.000000  49316.000000  2885.000000  238276.00000

## Find the number of missing values in each column.

In [38]:
df.isna().sum()

Order_ID        0
Customer        0
City            3
Category        0
Product         0
Quantity        0
Price           0
Discount        5
Sales           0
Payment_Mode    0
Status          0
dtype: int64

## Display only the Customer, City, and Sales columns.

In [41]:
df[["Customer","City","Sales"]]

   Customer       City   Sales
0    Vikram  Hyderabad    2644
1      Neha     Mumbai   31501
2     Sneha      Delhi   79741
3     Rohan    Chennai   67932
4    Vikram       Pune  117559
..      ...        ...     ...
95    Meera      Delhi   51392
96    Karan  Bangalore   88585
97   Vikram      Delhi   82377
98    Karan     Mumbai  131041
99    Sneha     Mumbai  120981

[100 rows x 3 columns]

## Level 2: Filtering

### Display all orders from Delhi. ###

In [43]:
df[df["City"]=="Delhi"]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled
10,1011,Neha,Delhi,Furniture,Mouse,1,47795,1428.0,46367,Card,Cancelled
15,1016,Rohan,Delhi,Electronics,Keyboard,1,38341,NaN,35948,COD,Delivered
20,1021,Rohan,Delhi,Furniture,Jacket,5,32979,1836.0,163059,UPI,Delivered
26,1027,Meera,Delhi,Clothing,Keyboard,5,47820,2286.0,236814,EMI,Cancelled
58,1059,Anjali,Delhi,Electronics,Desk,3,1562,1646.0,3040,COD,Pending
60,1061,Neha,Delhi,Clothing,Mobile,4,24744,2797.0,96179,UPI,Delivered
61,1062,Anjali,Delhi,Clothing,Table,2,22045,2410.0,41680,EMI,Delivered
62,1063,Priya,Delhi,Electronics,Table,3,22189,1774.0,64793,COD,Pending
65,1066,Meera,Delhi,Clothing,Mouse,1,37997,2786.0,35211,UPI,Delivered
68,1069,Vikram,Delhi,Electronics,Chair,3,38602,1654.0,114152,UPI,Delivered
72,1073,Priya,Delhi,Furniture,Mobile,1,7301,1062.0,6239,COD,Cancelled
75,1076,Meera,Delhi,Electronics,Desk,3,48636,1254.0,144654,Card,Pending
81,1082,Karan,Delhi,Furniture,Monitor,5,44761,2072.0,221733,COD,Cancelled
83,1084,Amit,Delhi,Furniture,Keyboard,2,22177,66.0,44288,Card,Delivered
85,1086,Sneha,Delhi,Electronics,Jacket,1,39581,2156.0,37425,EMI,Cancelled
92,1093,Rohan,Delhi,Clothing,Mouse,3,28795,622.0,85763,EMI,Delivered
94,1095,Vikram,Delhi,Electronics,Jacket,4,42848,2642.0,168750,EMI,Delivered
95,1096,Meera,Delhi,Clothing,Table,2,26932,2472.0,51392,EMI,Delivered
97,1098,Vikram,Delhi,Furniture,Desk,2,41959,1541.0,82377,EMI,Delivered

### Display all Electronics products ###

In [44]:
df[df["Category"]=="Electronics"]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered
8,1009,Sneha,Bangalore,Electronics,Laptop,4,19388,681.0,76871,UPI,Delivered
15,1016,Rohan,Delhi,Electronics,Keyboard,1,38341,NaN,35948,COD,Delivered
18,1019,Anjali,Chennai,Electronics,Mobile,1,23690,1101.0,22589,COD,Delivered
24,1025,Karan,Pune,Electronics,Laptop,2,6144,1144.0,11144,Card,Delivered
25,1026,Amit,Bangalore,Electronics,Table,3,43786,2261.0,129097,EMI,Delivered
28,1029,Vikram,Pune,Electronics,Laptop,5,21852,2397.0,106863,UPI,Pending
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered
38,1039,Priya,Bangalore,Electronics,Chair,4,14423,1890.0,55802,COD,Pending
41,1042,Priya,Mumbai,Electronics,Chair,2,24966,2766.0,47166,UPI,Delivered
43,1044,Karan,Pune,Electronics,Chair,5,4860,638.0,23662,UPI,Delivered
44,1045,Meera,Chennai,Electronics,Desk,4,35770,55.0,143025,Card,Cancelled
53,1054,Priya,Chennai,Electronics,Desk,5,11630,2746.0,55404,COD,Pending
54,1055,Sneha,Chennai,Electronics,Mouse,4,22472,1335.0,88553,UPI,Delivered
56,1057,Priya,Mumbai,Electronics,Mobile,1,1667,1030.0,637,Card,Delivered
58,1059,Anjali,Delhi,Electronics,Desk,3,1562,1646.0,3040,COD,Pending
59,1060,Meera,Chennai,Electronics,Shoes,4,19040,918.0,75242,EMI,Delivered
62,1063,Priya,Delhi,Electronics,Table,3,22189,1774.0,64793,COD,Pending
63,1064,Meera,Bangalore,Electronics,Laptop,4,11674,1531.0,45165,COD,Delivered
68,1069,Vikram,Delhi,Electronics,Chair,3,38602,1654.0,114152,UPI,Delivered
70,1071,Sneha,Chennai,Electronics,Monitor,4,37598,2075.0,148317,Card,Delivered
75,1076,Meera,Delhi,Electronics,Desk,3,48636,1254.0,144654,Card,Pending
77,1078,Karan,Mumbai,Electronics,Monitor,5,17837,125.0,89060,COD,Delivered
78,1079,Amit,Hyderabad,Electronics,Laptop,5,35807,2859.0,176176,EMI,Pending
85,1086,Sneha,Delhi,Electronics,Jacket,1,39581,2156.0,37425,EMI,Cancelled
86,1087,Rahul,Mumbai,Electronics,Keyboard,2,28069,1169.0,54969,EMI,Delivered
87,1088,Amit,Hyderabad,Electronics,Keyboard,5,23822,2158.0,116952,Card,Delivered
88,1089,Sneha,Hyderabad,Electronics,Shoes,2,19565,2275.0,36855,EMI,Delivered
90,1091,Rahul,Mumbai,Electronics,Monitor,2,23056,1493.0,44619,EMI,Delivered
93,1094,Meera,Pune,Electronics,Shoes,1,14307,2795.0,11512,Card,Delivered
94,1095,Vikram,Delhi,Electronics,Jacket,4,42848,2642.0,168750,EMI,Delivered

## Display all orders where the Status is Pending.

In [46]:
df[df["Status"]=="Pending"]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
7,1008,Vikram,Chennai,Furniture,Laptop,1,39256,603.0,38653,COD,Pending
11,1012,Sneha,Bangalore,Clothing,Table,2,49316,2885.0,95747,COD,Pending
13,1014,Rahul,Chennai,Clothing,Laptop,1,20963,2280.0,18683,Card,Pending
17,1018,Sneha,Mumbai,Furniture,Mouse,5,35411,1968.0,175087,Card,Pending
21,1022,Amit,Mumbai,Furniture,Laptop,5,45311,2841.0,223714,Card,Pending
27,1028,Rahul,Hyderabad,Furniture,Shoes,1,3414,1079.0,2335,EMI,Pending
28,1029,Vikram,Pune,Electronics,Laptop,5,21852,2397.0,106863,UPI,Pending
33,1034,Rahul,Bangalore,Clothing,Monitor,5,47459,NaN,236246,COD,Pending
34,1035,Vikram,Pune,Clothing,Desk,4,1228,2851.0,2061,UPI,Pending
38,1039,Priya,Bangalore,Electronics,Chair,4,14423,1890.0,55802,COD,Pending
40,1041,Karan,Hyderabad,Furniture,Shoes,5,7900,1715.0,37785,UPI,Pending
53,1054,Priya,Chennai,Electronics,Desk,5,11630,2746.0,55404,COD,Pending
55,1056,Neha,Bangalore,Furniture,Chair,2,40919,882.0,80956,EMI,Pending
58,1059,Anjali,Delhi,Electronics,Desk,3,1562,1646.0,3040,COD,Pending
62,1063,Priya,Delhi,Electronics,Table,3,22189,1774.0,64793,COD,Pending
64,1065,Priya,Chennai,Clothing,Jacket,1,23425,NaN,20572,EMI,Pending
75,1076,Meera,Delhi,Electronics,Desk,3,48636,1254.0,144654,Card,Pending
78,1079,Amit,Hyderabad,Electronics,Laptop,5,35807,2859.0,176176,EMI,Pending
98,1099,Karan,Mumbai,Clothing,Mouse,5,26756,2739.0,131041,Card,Pending

### Display orders where Sales are greater than 50000 and sort the values by Sales desc ###

In [50]:
df[df["Sales"]>50000].sort_values(by="Sales",ascending= False)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
95,1096,Meera,Delhi,Clothing,Table,2,26932,2472.0,51392,EMI,Delivered
91,1092,Amit,Bangalore,Clothing,Table,2,27462,2081.0,52843,UPI,Delivered
5,1006,Meera,Bangalore,Clothing,Chair,2,27884,1028.0,54740,EMI,Delivered
86,1087,Rahul,Mumbai,Electronics,Keyboard,2,28069,1169.0,54969,EMI,Delivered
53,1054,Priya,Chennai,Electronics,Desk,5,11630,2746.0,55404,COD,Pending
38,1039,Priya,Bangalore,Electronics,Chair,4,14423,1890.0,55802,COD,Pending
49,1050,Sneha,Hyderabad,Furniture,Monitor,3,21864,2125.0,63467,UPI,Delivered
62,1063,Priya,Delhi,Electronics,Table,3,22189,1774.0,64793,COD,Pending
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled
67,1068,Sneha,Pune,Furniture,Chair,3,24214,1215.0,71427,COD,Delivered
71,1072,Rohan,Bangalore,Furniture,Mouse,3,24894,713.0,73969,COD,Delivered
42,1043,Meera,Mumbai,Clothing,Desk,2,37439,302.0,74576,EMI,Delivered
50,1051,Rahul,Hyderabad,Clothing,Shoes,2,37759,364.0,75154,EMI,Delivered
59,1060,Meera,Chennai,Electronics,Shoes,4,19040,918.0,75242,EMI,Delivered
8,1009,Sneha,Bangalore,Electronics,Laptop,4,19388,681.0,76871,UPI,Delivered
36,1037,Karan,Pune,Clothing,Jacket,2,40454,2055.0,78853,Card,Cancelled
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled
23,1024,Anjali,Hyderabad,Clothing,Mouse,4,20650,2094.0,80506,Card,Delivered
55,1056,Neha,Bangalore,Furniture,Chair,2,40919,882.0,80956,EMI,Pending
97,1098,Vikram,Delhi,Furniture,Desk,2,41959,1541.0,82377,EMI,Delivered
92,1093,Rohan,Delhi,Clothing,Mouse,3,28795,622.0,85763,EMI,Delivered
54,1055,Sneha,Chennai,Electronics,Mouse,4,22472,1335.0,88553,UPI,Delivered
96,1097,Karan,Bangalore,Clothing,Chair,5,18249,2660.0,88585,Card,Delivered
77,1078,Karan,Mumbai,Electronics,Monitor,5,17837,125.0,89060,COD,Delivered
76,1077,Karan,Bangalore,Clothing,Desk,4,24125,2133.0,94367,Card,Delivered
11,1012,Sneha,Bangalore,Clothing,Table,2,49316,2885.0,95747,COD,Pending
60,1061,Neha,Delhi,Clothing,Mobile,4,24744,2797.0,96179,UPI,Delivered
28,1029,Vikram,Pune,Electronics,Laptop,5,21852,2397.0,106863,UPI,Pending
22,1023,Meera,Mumbai,Clothing,Keyboard,3,36708,2296.0,107828,EMI,Cancelled
57,1058,Anjali,Hyderabad,Furniture,Jacket,4,27692,NaN,109742,UPI,Delivered
68,1069,Vikram,Delhi,Electronics,Chair,3,38602,1654.0,114152,UPI,Delivered
87,1088,Amit,Hyderabad,Electronics,Keyboard,5,23822,2158.0,116952,Card,Delivered
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered
99,1100,Sneha,Mumbai,Furniture,Laptop,3,40762,1305.0,120981,EMI,Delivered
25,1026,Amit,Bangalore,Electronics,Table,3,43786,2261.0,129097,EMI,Delivered
46,1047,Priya,Pune,Clothing,Jacket,4,32807,525.0,130703,Card,Delivered
98,1099,Karan,Mumbai,Clothing,Mouse,5,26756,2739.0,131041,Card,Pending
84,1085,Sneha,Chennai,Clothing,Laptop,3,47232,232.0,141464,EMI,Delivered
44,1045,Meera,Chennai,Electronics,Desk,4,35770,55.0,143025,Card,Cancelled
75,1076,Meera,Delhi,Electronics,Desk,3,48636,1254.0,144654,Card,Pending
70,1071,Sneha,Chennai,Electronics,Monitor,4,37598,2075.0,148317,Card,Delivered
52,1053,Neha,Hyderabad,Furniture,Shoes,5,32167,525.0,160310,UPI,Delivered
20,1021,Rohan,Delhi,Furniture,Jacket,5,32979,1836.0,163059,UPI,Delivered
32,1033,Rohan,Pune,Furniture,Desk,4,42055,336.0,167884,UPI,Delivered
94,1095,Vikram,Delhi,Electronics,Jacket,4,42848,2642.0,168750,EMI,Delivered
17,1018,Sneha,Mumbai,Furniture,Mouse,5,35411,1968.0,175087,Card,Pending
78,1079,Amit,Hyderabad,Electronics,Laptop,5,35807,2859.0,176176,EMI,Pending
9,1010,Rohan,Bangalore,Furniture,Keyboard,5,36235,2581.0,178594,EMI,Delivered
29,1030,Neha,Hyderabad,Clothing,Mouse,4,46852,106.0,187302,COD,Delivered
81,1082,Karan,Delhi,Furniture,Monitor,5,44761,2072.0,221733,COD,Cancelled
6,1007,Rahul,Hyderabad,Furniture,Keyboard,5,44925,NaN,223136,COD,Delivered
21,1022,Amit,Mumbai,Furniture,Laptop,5,45311,2841.0,223714,Card,Pending
30,1031,Karan,Chennai,Clothing,Chair,5,45412,2878.0,224182,UPI,Delivered
33,1034,Rahul,Bangalore,Clothing,Monitor,5,47459,NaN,236246,COD,Pending
26,1027,Meera,Delhi,Clothing,Keyboard,5,47820,2286.0,236814,EMI,Cancelled
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered

In [ ]:
Display orders where the Payment_Mode is UPI.

In [53]:
df[df["Payment_Mode"]=="UPI"]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered
1,1002,Neha,Mumbai,Clothing,Monitor,4,8043,671.0,31501,UPI,Delivered
8,1009,Sneha,Bangalore,Electronics,Laptop,4,19388,681.0,76871,UPI,Delivered
19,1020,Priya,NaN,Furniture,Keyboard,5,7857,1753.0,37532,UPI,Delivered
20,1021,Rohan,Delhi,Furniture,Jacket,5,32979,1836.0,163059,UPI,Delivered
28,1029,Vikram,Pune,Electronics,Laptop,5,21852,2397.0,106863,UPI,Pending
30,1031,Karan,Chennai,Clothing,Chair,5,45412,2878.0,224182,UPI,Delivered
32,1033,Rohan,Pune,Furniture,Desk,4,42055,336.0,167884,UPI,Delivered
34,1035,Vikram,Pune,Clothing,Desk,4,1228,2851.0,2061,UPI,Pending
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered
40,1041,Karan,Hyderabad,Furniture,Shoes,5,7900,1715.0,37785,UPI,Pending
41,1042,Priya,Mumbai,Electronics,Chair,2,24966,2766.0,47166,UPI,Delivered
43,1044,Karan,Pune,Electronics,Chair,5,4860,638.0,23662,UPI,Delivered
45,1046,Rohan,NaN,Furniture,Laptop,2,17601,725.0,34477,UPI,Delivered
49,1050,Sneha,Hyderabad,Furniture,Monitor,3,21864,2125.0,63467,UPI,Delivered
51,1052,Amit,Hyderabad,Clothing,Desk,1,24076,2713.0,21363,UPI,Delivered
52,1053,Neha,Hyderabad,Furniture,Shoes,5,32167,525.0,160310,UPI,Delivered
54,1055,Sneha,Chennai,Electronics,Mouse,4,22472,1335.0,88553,UPI,Delivered
57,1058,Anjali,Hyderabad,Furniture,Jacket,4,27692,NaN,109742,UPI,Delivered
60,1061,Neha,Delhi,Clothing,Mobile,4,24744,2797.0,96179,UPI,Delivered
65,1066,Meera,Delhi,Clothing,Mouse,1,37997,2786.0,35211,UPI,Delivered
68,1069,Vikram,Delhi,Electronics,Chair,3,38602,1654.0,114152,UPI,Delivered
69,1070,Karan,Bangalore,Clothing,Shoes,5,9424,484.0,46636,UPI,Delivered
73,1074,Rohan,Chennai,Clothing,Desk,1,38114,1976.0,36138,UPI,Delivered
74,1075,Sneha,Pune,Furniture,Monitor,2,7231,1296.0,13166,UPI,Delivered
80,1081,Vikram,Chennai,Furniture,Desk,2,12016,2192.0,21840,UPI,Delivered
91,1092,Amit,Bangalore,Clothing,Table,2,27462,2081.0,52843,UPI,Delivered

### Display Electronics orders from Delhi ###

In [56]:
df[(df["Category"]=="Electronics") & (df["City"]=="Delhi")]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled
15,1016,Rohan,Delhi,Electronics,Keyboard,1,38341,NaN,35948,COD,Delivered
58,1059,Anjali,Delhi,Electronics,Desk,3,1562,1646.0,3040,COD,Pending
62,1063,Priya,Delhi,Electronics,Table,3,22189,1774.0,64793,COD,Pending
68,1069,Vikram,Delhi,Electronics,Chair,3,38602,1654.0,114152,UPI,Delivered
75,1076,Meera,Delhi,Electronics,Desk,3,48636,1254.0,144654,Card,Pending
85,1086,Sneha,Delhi,Electronics,Jacket,1,39581,2156.0,37425,EMI,Cancelled
94,1095,Vikram,Delhi,Electronics,Jacket,4,42848,2642.0,168750,EMI,Delivered

### Display Clothing orders with Sales greater than 10000 ###

In [57]:
df[(df["Category"]=="Clothing") & (df["Sales"] > 10000)]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
1,1002,Neha,Mumbai,Clothing,Monitor,4,8043,671.0,31501,UPI,Delivered
5,1006,Meera,Bangalore,Clothing,Chair,2,27884,1028.0,54740,EMI,Delivered
11,1012,Sneha,Bangalore,Clothing,Table,2,49316,2885.0,95747,COD,Pending
12,1013,Sneha,Pune,Clothing,Mouse,2,18006,2692.0,33320,COD,Cancelled
13,1014,Rahul,Chennai,Clothing,Laptop,1,20963,2280.0,18683,Card,Pending
14,1015,Anjali,Bangalore,Clothing,Laptop,2,18455,523.0,36387,Card,Delivered
16,1017,Priya,Pune,Clothing,Monitor,5,5604,2593.0,25427,COD,Cancelled
22,1023,Meera,Mumbai,Clothing,Keyboard,3,36708,2296.0,107828,EMI,Cancelled
23,1024,Anjali,Hyderabad,Clothing,Mouse,4,20650,2094.0,80506,Card,Delivered
26,1027,Meera,Delhi,Clothing,Keyboard,5,47820,2286.0,236814,EMI,Cancelled
29,1030,Neha,Hyderabad,Clothing,Mouse,4,46852,106.0,187302,COD,Delivered
30,1031,Karan,Chennai,Clothing,Chair,5,45412,2878.0,224182,UPI,Delivered
31,1032,Rahul,Pune,Clothing,Mobile,1,14897,47.0,14850,COD,Delivered
33,1034,Rahul,Bangalore,Clothing,Monitor,5,47459,NaN,236246,COD,Pending
36,1037,Karan,Pune,Clothing,Jacket,2,40454,2055.0,78853,Card,Cancelled
39,1040,Neha,Chennai,Clothing,Monitor,1,17279,1276.0,16003,EMI,Cancelled
42,1043,Meera,Mumbai,Clothing,Desk,2,37439,302.0,74576,EMI,Delivered
46,1047,Priya,Pune,Clothing,Jacket,4,32807,525.0,130703,Card,Delivered
47,1048,Neha,Chennai,Clothing,Laptop,2,5986,473.0,11499,Card,Delivered
50,1051,Rahul,Hyderabad,Clothing,Shoes,2,37759,364.0,75154,EMI,Delivered
51,1052,Amit,Hyderabad,Clothing,Desk,1,24076,2713.0,21363,UPI,Delivered
60,1061,Neha,Delhi,Clothing,Mobile,4,24744,2797.0,96179,UPI,Delivered
61,1062,Anjali,Delhi,Clothing,Table,2,22045,2410.0,41680,EMI,Delivered
64,1065,Priya,Chennai,Clothing,Jacket,1,23425,NaN,20572,EMI,Pending
65,1066,Meera,Delhi,Clothing,Mouse,1,37997,2786.0,35211,UPI,Delivered
66,1067,Neha,Hyderabad,Clothing,Shoes,5,9848,1906.0,47334,Card,Delivered
69,1070,Karan,Bangalore,Clothing,Shoes,5,9424,484.0,46636,UPI,Delivered
73,1074,Rohan,Chennai,Clothing,Desk,1,38114,1976.0,36138,UPI,Delivered
76,1077,Karan,Bangalore,Clothing,Desk,4,24125,2133.0,94367,Card,Delivered
84,1085,Sneha,Chennai,Clothing,Laptop,3,47232,232.0,141464,EMI,Delivered
91,1092,Amit,Bangalore,Clothing,Table,2,27462,2081.0,52843,UPI,Delivered
92,1093,Rohan,Delhi,Clothing,Mouse,3,28795,622.0,85763,EMI,Delivered
95,1096,Meera,Delhi,Clothing,Table,2,26932,2472.0,51392,EMI,Delivered
96,1097,Karan,Bangalore,Clothing,Chair,5,18249,2660.0,88585,Card,Delivered
98,1099,Karan,Mumbai,Clothing,Mouse,5,26756,2739.0,131041,Card,Pending

### Display orders where Quantity is at least 3.

In [60]:
df[df["Quantity"]<=3]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled
5,1006,Meera,Bangalore,Clothing,Chair,2,27884,1028.0,54740,EMI,Delivered
7,1008,Vikram,Chennai,Furniture,Laptop,1,39256,603.0,38653,COD,Pending
10,1011,Neha,Delhi,Furniture,Mouse,1,47795,1428.0,46367,Card,Cancelled
11,1012,Sneha,Bangalore,Clothing,Table,2,49316,2885.0,95747,COD,Pending
12,1013,Sneha,Pune,Clothing,Mouse,2,18006,2692.0,33320,COD,Cancelled
13,1014,Rahul,Chennai,Clothing,Laptop,1,20963,2280.0,18683,Card,Pending
14,1015,Anjali,Bangalore,Clothing,Laptop,2,18455,523.0,36387,Card,Delivered
15,1016,Rohan,Delhi,Electronics,Keyboard,1,38341,NaN,35948,COD,Delivered
18,1019,Anjali,Chennai,Electronics,Mobile,1,23690,1101.0,22589,COD,Delivered
22,1023,Meera,Mumbai,Clothing,Keyboard,3,36708,2296.0,107828,EMI,Cancelled
24,1025,Karan,Pune,Electronics,Laptop,2,6144,1144.0,11144,Card,Delivered
25,1026,Amit,Bangalore,Electronics,Table,3,43786,2261.0,129097,EMI,Delivered
27,1028,Rahul,Hyderabad,Furniture,Shoes,1,3414,1079.0,2335,EMI,Pending
31,1032,Rahul,Pune,Clothing,Mobile,1,14897,47.0,14850,COD,Delivered
35,1036,Rohan,Hyderabad,Clothing,Mouse,2,1198,1280.0,1116,EMI,Cancelled
36,1037,Karan,Pune,Clothing,Jacket,2,40454,2055.0,78853,Card,Cancelled
39,1040,Neha,Chennai,Clothing,Monitor,1,17279,1276.0,16003,EMI,Cancelled
41,1042,Priya,Mumbai,Electronics,Chair,2,24966,2766.0,47166,UPI,Delivered
42,1043,Meera,Mumbai,Clothing,Desk,2,37439,302.0,74576,EMI,Delivered
45,1046,Rohan,NaN,Furniture,Laptop,2,17601,725.0,34477,UPI,Delivered
47,1048,Neha,Chennai,Clothing,Laptop,2,5986,473.0,11499,Card,Delivered
48,1049,Vikram,NaN,Furniture,Mobile,2,8835,27.0,17643,EMI,Delivered
49,1050,Sneha,Hyderabad,Furniture,Monitor,3,21864,2125.0,63467,UPI,Delivered
50,1051,Rahul,Hyderabad,Clothing,Shoes,2,37759,364.0,75154,EMI,Delivered
51,1052,Amit,Hyderabad,Clothing,Desk,1,24076,2713.0,21363,UPI,Delivered
55,1056,Neha,Bangalore,Furniture,Chair,2,40919,882.0,80956,EMI,Pending
56,1057,Priya,Mumbai,Electronics,Mobile,1,1667,1030.0,637,Card,Delivered
58,1059,Anjali,Delhi,Electronics,Desk,3,1562,1646.0,3040,COD,Pending
61,1062,Anjali,Delhi,Clothing,Table,2,22045,2410.0,41680,EMI,Delivered
62,1063,Priya,Delhi,Electronics,Table,3,22189,1774.0,64793,COD,Pending
64,1065,Priya,Chennai,Clothing,Jacket,1,23425,NaN,20572,EMI,Pending
65,1066,Meera,Delhi,Clothing,Mouse,1,37997,2786.0,35211,UPI,Delivered
67,1068,Sneha,Pune,Furniture,Chair,3,24214,1215.0,71427,COD,Delivered
68,1069,Vikram,Delhi,Electronics,Chair,3,38602,1654.0,114152,UPI,Delivered
71,1072,Rohan,Bangalore,Furniture,Mouse,3,24894,713.0,73969,COD,Delivered
72,1073,Priya,Delhi,Furniture,Mobile,1,7301,1062.0,6239,COD,Cancelled
73,1074,Rohan,Chennai,Clothing,Desk,1,38114,1976.0,36138,UPI,Delivered
74,1075,Sneha,Pune,Furniture,Monitor,2,7231,1296.0,13166,UPI,Delivered
75,1076,Meera,Delhi,Electronics,Desk,3,48636,1254.0,144654,Card,Pending
80,1081,Vikram,Chennai,Furniture,Desk,2,12016,2192.0,21840,UPI,Delivered
82,1083,Sneha,Hyderabad,Furniture,Monitor,3,2042,1603.0,4523,EMI,Delivered
83,1084,Amit,Delhi,Furniture,Keyboard,2,22177,66.0,44288,Card,Delivered
84,1085,Sneha,Chennai,Clothing,Laptop,3,47232,232.0,141464,EMI,Delivered
85,1086,Sneha,Delhi,Electronics,Jacket,1,39581,2156.0,37425,EMI,Cancelled
86,1087,Rahul,Mumbai,Electronics,Keyboard,2,28069,1169.0,54969,EMI,Delivered
88,1089,Sneha,Hyderabad,Electronics,Shoes,2,19565,2275.0,36855,EMI,Delivered
89,1090,Rahul,Chennai,Furniture,Table,2,18424,110.0,36738,EMI,Delivered
90,1091,Rahul,Mumbai,Electronics,Monitor,2,23056,1493.0,44619,EMI,Delivered
91,1092,Amit,Bangalore,Clothing,Table,2,27462,2081.0,52843,UPI,Delivered
92,1093,Rohan,Delhi,Clothing,Mouse,3,28795,622.0,85763,EMI,Delivered
93,1094,Meera,Pune,Electronics,Shoes,1,14307,2795.0,11512,Card,Delivered
95,1096,Meera,Delhi,Clothing,Table,2,26932,2472.0,51392,EMI,Delivered
97,1098,Vikram,Delhi,Furniture,Desk,2,41959,1541.0,82377,EMI,Delivered
99,1100,Sneha,Mumbai,Furniture,Laptop,3,40762,1305.0,120981,EMI,Delivered

## Display all orders except those from Mumbai.

In [61]:
df[df["City"]!="Mumbai"]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered
5,1006,Meera,Bangalore,Clothing,Chair,2,27884,1028.0,54740,EMI,Delivered
...,...,...,...,...,...,...,...,...,...,...,...
93,1094,Meera,Pune,Electronics,Shoes,1,14307,2795.0,11512,Card,Delivered
94,1095,Vikram,Delhi,Electronics,Jacket,4,42848,2642.0,168750,EMI,Delivered
95,1096,Meera,Delhi,Clothing,Table,2,26932,2472.0,51392,EMI,Delivered
96,1097,Karan,Bangalore,Clothing,Chair,5,18249,2660.0,88585,Card,Delivered
97,1098,Vikram,Delhi,Furniture,Desk,2,41959,1541.0,82377,EMI,Delivered

## Display all rows where Discount is missing.

In [68]:
df[df["Discount"].isna()]

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
6,1007,Rahul,Hyderabad,Furniture,Keyboard,5,44925,NaN,223136,COD,Delivered
15,1016,Rohan,Delhi,Electronics,Keyboard,1,38341,NaN,35948,COD,Delivered
33,1034,Rahul,Bangalore,Clothing,Monitor,5,47459,NaN,236246,COD,Pending
57,1058,Anjali,Hyderabad,Furniture,Jacket,4,27692,NaN,109742,UPI,Delivered
64,1065,Priya,Chennai,Clothing,Jacket,1,23425,NaN,20572,EMI,Pending

## Level 3: Sorting (21–25)

## Sort the dataset by Sales in descending order.

In [74]:
df.sort_values(by="Sales",ascending = False)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered
26,1027,Meera,Delhi,Clothing,Keyboard,5,47820,2286.0,236814,EMI,Cancelled
33,1034,Rahul,Bangalore,Clothing,Monitor,5,47459,NaN,236246,COD,Pending
30,1031,Karan,Chennai,Clothing,Chair,5,45412,2878.0,224182,UPI,Delivered
21,1022,Amit,Mumbai,Furniture,Laptop,5,45311,2841.0,223714,Card,Pending
...,...,...,...,...,...,...,...,...,...,...,...
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered
27,1028,Rahul,Hyderabad,Furniture,Shoes,1,3414,1079.0,2335,EMI,Pending
34,1035,Vikram,Pune,Clothing,Desk,4,1228,2851.0,2061,UPI,Pending
35,1036,Rohan,Hyderabad,Clothing,Mouse,2,1198,1280.0,1116,EMI,Cancelled
56,1057,Priya,Mumbai,Electronics,Mobile,1,1667,1030.0,637,Card,Delivered

## Sort the dataset by Price in ascending order.

In [75]:
df.sort_values(by="Price")

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered
35,1036,Rohan,Hyderabad,Clothing,Mouse,2,1198,1280.0,1116,EMI,Cancelled
34,1035,Vikram,Pune,Clothing,Desk,4,1228,2851.0,2061,UPI,Pending
58,1059,Anjali,Delhi,Electronics,Desk,3,1562,1646.0,3040,COD,Pending
56,1057,Priya,Mumbai,Electronics,Mobile,1,1667,1030.0,637,Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered
10,1011,Neha,Delhi,Furniture,Mouse,1,47795,1428.0,46367,Card,Cancelled
26,1027,Meera,Delhi,Clothing,Keyboard,5,47820,2286.0,236814,EMI,Cancelled
75,1076,Meera,Delhi,Electronics,Desk,3,48636,1254.0,144654,Card,Pending
11,1012,Sneha,Bangalore,Clothing,Table,2,49316,2885.0,95747,COD,Pending

## Sort first by City and then by Sales (highest first).

In [83]:
df.sort_values(by=["City","Sales"],ascending = [False,False])

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
32,1033,Rohan,Pune,Furniture,Desk,4,42055,336.0,167884,UPI,Delivered
46,1047,Priya,Pune,Clothing,Jacket,4,32807,525.0,130703,Card,Delivered
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered
28,1029,Vikram,Pune,Electronics,Laptop,5,21852,2397.0,106863,UPI,Pending
36,1037,Karan,Pune,Clothing,Jacket,2,40454,2055.0,78853,Card,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...
14,1015,Anjali,Bangalore,Clothing,Laptop,2,18455,523.0,36387,Card,Delivered
79,1080,Karan,Bangalore,Furniture,Table,4,7556,536.0,29688,COD,Cancelled
19,1020,Priya,NaN,Furniture,Keyboard,5,7857,1753.0,37532,UPI,Delivered
45,1046,Rohan,NaN,Furniture,Laptop,2,17601,725.0,34477,UPI,Delivered
48,1049,Vikram,NaN,Furniture,Mobile,2,8835,27.0,17643,EMI,Delivered

## Find the top 10 highest sales.

In [97]:
df.sort_values(by="Sales", ascending = False).head(10)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered
26,1027,Meera,Delhi,Clothing,Keyboard,5,47820,2286.0,236814,EMI,Cancelled
33,1034,Rahul,Bangalore,Clothing,Monitor,5,47459,NaN,236246,COD,Pending
30,1031,Karan,Chennai,Clothing,Chair,5,45412,2878.0,224182,UPI,Delivered
21,1022,Amit,Mumbai,Furniture,Laptop,5,45311,2841.0,223714,Card,Pending
6,1007,Rahul,Hyderabad,Furniture,Keyboard,5,44925,NaN,223136,COD,Delivered
81,1082,Karan,Delhi,Furniture,Monitor,5,44761,2072.0,221733,COD,Cancelled
29,1030,Neha,Hyderabad,Clothing,Mouse,4,46852,106.0,187302,COD,Delivered
9,1010,Rohan,Bangalore,Furniture,Keyboard,5,36235,2581.0,178594,EMI,Delivered
78,1079,Amit,Hyderabad,Electronics,Laptop,5,35807,2859.0,176176,EMI,Pending

## Find the 5 cheapest products.

In [100]:
df.sort_values(by="Price", ascending = True).head(5)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment_Mode,Status
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered
35,1036,Rohan,Hyderabad,Clothing,Mouse,2,1198,1280.0,1116,EMI,Cancelled
34,1035,Vikram,Pune,Clothing,Desk,4,1228,2851.0,2061,UPI,Pending
58,1059,Anjali,Delhi,Electronics,Desk,3,1562,1646.0,3040,COD,Pending
56,1057,Priya,Mumbai,Electronics,Mobile,1,1667,1030.0,637,Card,Delivered

## Level 4: Column Operations

### Rename the column Payment_Mode to Payment.

In [102]:
df.rename(columns={"Payment_Mode": "Payment"},inplace=True)

In [123]:
df.head()

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment,Status,GST,Final_Amount
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered,164.16,2808.16
1,1002,Neha,Mumbai,Clothing,Monitor,4,8043,671.0,31501,UPI,Delivered,1447.74,32948.74
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled,7353.90,87094.90
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled,6119.28,74051.28
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered,4328.64,121887.64

### Create a new column named GST equal to 18% of Price.

In [106]:
df["GST"] = df["Price"] * 0.18

In [122]:
df.head()

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment,Status,GST,Final_Amount
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered,164.16,2808.16
1,1002,Neha,Mumbai,Clothing,Monitor,4,8043,671.0,31501,UPI,Delivered,1447.74,32948.74
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled,7353.90,87094.90
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled,6119.28,74051.28
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered,4328.64,121887.64

### Create a new column called Final_Amount = Sales + GST.

In [117]:
df["Final_Amount"]=df["Sales"] + df["GST"]

In [121]:
df.head()

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment,Status,GST,Final_Amount
0,1001,Vikram,Hyderabad,Furniture,Monitor,3,912,92.0,2644,UPI,Delivered,164.16,2808.16
1,1002,Neha,Mumbai,Clothing,Monitor,4,8043,671.0,31501,UPI,Delivered,1447.74,32948.74
2,1003,Sneha,Delhi,Electronics,Mouse,2,40855,1969.0,79741,EMI,Cancelled,7353.90,87094.90
3,1004,Rohan,Chennai,Electronics,Monitor,2,33996,60.0,67932,EMI,Cancelled,6119.28,74051.28
4,1005,Vikram,Pune,Electronics,Jacket,5,24048,2681.0,117559,Card,Delivered,4328.64,121887.64

### Convert the Quantity column to string.

In [125]:
df.dtypes

Order_ID          int64
Customer         object
City             object
Category         object
Product          object
Quantity          int32
Price             int32
Discount        float64
Sales             int32
Payment          object
Status           object
GST             float64
Final_Amount    float64
dtype: object

In [126]:
df["Quantity"] = df["Quantity"].astype(str)

In [127]:
df.dtypes

Order_ID          int64
Customer         object
City             object
Category         object
Product          object
Quantity         object
Price             int32
Discount        float64
Sales             int32
Payment          object
Status           object
GST             float64
Final_Amount    float64
dtype: object

### Convert the Quantity column back to integer.

In [128]:
df["Quantity"] = df["Quantity"].astype(int)

In [129]:
df.dtypes

Order_ID          int64
Customer         object
City             object
Category         object
Product          object
Quantity          int64
Price             int32
Discount        float64
Sales             int32
Payment          object
Status           object
GST             float64
Final_Amount    float64
dtype: object

## Level 5: Aggregations

### Find the total Sales.

In [131]:
df["Sales"].sum()

np.int64(7886370)

### Find the average Price.

In [133]:
df["Price"].mean()

np.float64(25577.69)

### Find the maximum Sales.

In [134]:
df["Sales"].max()

238276

### Find the minimum Discount.

In [135]:
df["Discount"].min()

27.0

### Count the total number of orders.

In [140]:
df["Order_ID"].count()

np.int64(100)

### Count the number of unique customers.

In [142]:
df["Customer"].nunique()

10

## Level 6: GroupBy

### Find total Sales for each City.

In [149]:
df.groupby("City")["Sales"].sum()

City
Bangalore    1613969
Chennai      1166834
Delhi        1759605
Hyderabad    1346700
Mumbai       1101179
Pune          808431
Name: Sales, dtype: int32

### Find average Price for each Category.

In [152]:
df.groupby("Category")["Price"].mean()

Category
Clothing       26255.216216
Electronics    25450.333333
Furniture      24882.166667
Name: Price, dtype: float64

### Find total Quantity sold in each Category.

In [154]:
df.groupby("Category")["Quantity"].sum()

Category
Clothing       108
Electronics    106
Furniture       95
Name: Quantity, dtype: int64

### Find the maximum Sales in each City.

In [155]:
df.groupby("City")["Sales"].max()

City
Bangalore    238276
Chennai      224182
Delhi        236814
Hyderabad    223136
Mumbai       223714
Pune         167884
Name: Sales, dtype: int32

### Count the number of orders in each Status.

In [156]:
df.groupby("Status")["Order_ID"].count()

Status
Cancelled    15
Delivered    66
Pending      19
Name: Order_ID, dtype: int64

### Find total Sales for each Payment Mode.

In [157]:
df.groupby("Payment")["Sales"].sum()

Payment
COD     1629538
Card    1901214
EMI     2302055
UPI     2053563
Name: Sales, dtype: int32

## Level 7: Pivot Tables

### Create a pivot table showing total Sales by City.

In [159]:
df.pivot_table(values="Sales", index="City",aggfunc="sum")

             Sales
City
Bangalore  1613969
Chennai    1166834
Delhi      1759605
Hyderabad  1346700
Mumbai     1101179
Pune        808431

### Create a pivot table showing average Price by Category.

In [160]:
df.pivot_table(values="Price",index="Category",aggfunc="mean")

                    Price
Category
Clothing     26255.216216
Electronics  25450.333333
Furniture    24882.166667

### Create a pivot table with City as rows and Category as columns showing total Sales.

In [165]:
df.pivot_table(values="Sales",index="City",columns="Category",aggfunc="sum")

Category   Clothing  Electronics  Furniture
City
Bangalore    705551       545211     363207
Chennai      468541       601062      97231
Delhi        547039       648503     564063
Hyderabad    412775       329983     603942
Mumbai       344946       236451     519782
Pune         285214       270740     252477

### Create a pivot table showing total Quantity by Payment Mode and Status.

In [170]:
df.pivot_table(values="Quantity",index="Payment",columns="Status",aggfunc="sum")

Status   Cancelled  Delivered  Pending
Payment
COD           17.0       27.0     23.0
Card           7.0       46.0     19.0
EMI           16.0       50.0      9.0
UPI            NaN       81.0     14.0

## Level 8: Value Counts & Missing Values

### Count how many orders belong to each Category.

In [176]:
df["Category"].value_counts()

Category
Clothing       37
Electronics    33
Furniture      30
Name: count, dtype: int64

### Count how many customers belong to each City.

In [177]:
df["City"].value_counts()

City
Delhi        20
Hyderabad    17
Chennai      17
Bangalore    17
Pune         14
Mumbai       12
Name: count, dtype: int64

In [178]:
df.groupby("City")["Customer"].nunique()

City
Bangalore    10
Chennai       9
Delhi         9
Hyderabad     8
Mumbai        7
Pune          7
Name: Customer, dtype: int64

### Replace all missing Discounts with 0.

In [179]:
df["Discount"].isna().sum()

np.int64(5)

In [180]:
df["Discount"]=df["Discount"].fillna(0)

In [181]:
df["Discount"].isna().sum()

np.int64(0)

### Drop all rows where City is missing.

In [183]:
df["City"].isna().sum()

np.int64(3)

In [215]:
df=df.dropna(subset=["City"])

In [216]:
df["City"].isna().sum()

np.int64(0)

## Bonus Challenge Questions

### Find the top 5 customers by total Sales.

In [195]:
df.sort_values(by="Sales",ascending=False).head(5)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment,Status,GST,Final_Amount
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered,8600.40,246876.40
26,1027,Meera,Delhi,Clothing,Keyboard,5,47820,2286.0,236814,EMI,Cancelled,8607.60,245421.60
33,1034,Rahul,Bangalore,Clothing,Monitor,5,47459,0.0,236246,COD,Pending,8542.62,244788.62
30,1031,Karan,Chennai,Clothing,Chair,5,45412,2878.0,224182,UPI,Delivered,8174.16,232356.16
21,1022,Amit,Mumbai,Furniture,Laptop,5,45311,2841.0,223714,Card,Pending,8155.98,231869.98

### Find which city generated the highest revenue.

In [198]:
df.sort_values(by="GST", ascending=False).head(1)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment,Status,GST,Final_Amount
11,1012,Sneha,Bangalore,Clothing,Table,2,49316,2885.0,95747,COD,Pending,8876.88,104623.88

### Find the most popular payment mode.

In [204]:
df["Payment"].value_counts().head(1)

Payment
EMI    30
Name: count, dtype: int64

### Find the average sales of Delivered vs Pending orders.

In [210]:
df[df["Status"].isin(["Delivered","Pending"])].groupby("Status")["Sales"].mean()

Status
Delivered    77049.196970
Pending      87874.315789
Name: Sales, dtype: float64

### Find the customer who placed the highest-value order.

### concise way to retrieve the highest-value rows.

In [213]:
df.nlargest(1,"Final_Amount")

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment,Status,GST,Final_Amount
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered,8600.4,246876.4

### another usual easy approach beginner level

In [212]:
df.sort_values("Final_Amount",ascending= False).head(1)

,Order_ID,Customer,City,Category,Product,Quantity,Price,Discount,Sales,Payment,Status,GST,Final_Amount
37,1038,Vikram,Bangalore,Electronics,Jacket,5,47780,624.0,238276,UPI,Delivered,8600.4,246876.4

### Find the percentage of Delivered, Pending, and Cancelled orders.

In [225]:
((df["Status"].value_counts()/len(df)) * 100).round(2)

Status
Delivered    64.95
Pending      19.59
Cancelled    15.46
Name: count, dtype: float64

### another concise method for the interview point of view

In [228]:
(df["Status"].value_counts(normalize=True) * 100).round(2)

Status
Delivered    64.95
Pending      19.59
Cancelled    15.46
Name: proportion, dtype: float64

### Find the top-selling category based on total Sales.

In [240]:
df.groupby("Category")["Sales"].sum().sort_values(ascending=False).head(1)

Category
Clothing    2764066
Name: Sales, dtype: int32

### another method

In [244]:
df.groupby("Category")["Sales"].sum().idxmax()

'Clothing'

### Which product appears most frequently?

In [247]:
df["Product"].value_counts().idxmax()

'Monitor'

### Find duplicate customers and count how many orders each placed.

In [262]:
df["Customer"].value_counts()[df["Customer"].value_counts() > 1]

Customer
Sneha     15
Karan     12
Meera     11
Vikram    10
Neha       9
Rohan      9
Rahul      9
Priya      9
Amit       7
Anjali     6
Name: count, dtype: int64

### another method

In [264]:
customer_orders = df.groupby("Customer")["Order_ID"].count().reset_index()
customer_orders[customer_orders["Order_ID"] > 1]

  Customer  Order_ID
0     Amit         7
1   Anjali         6
2    Karan        12
3    Meera        11
4     Neha         9
5    Priya         9
6    Rahul         9
7    Rohan         9
8    Sneha        15
9   Vikram        10

### Export the Electronics orders to a new CSV file.

In [269]:
df[df["Category"]=="Electronics"].to_csv(r"C:\Users\asang\Downloads\electronics_orders",index=False)